AllCops:
  TargetRubyVersion: 2.7
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Metrics/AbcSize:
#  Enabled: false
  Max: 26
Metrics/PerceivedComplexity:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Metrics/ClassLength:
  Max: 600
Style/ClassVars:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 12